# Module 15 Assignment Analysis
Anjali Khatri <br>
INST414 <br>
8/21/2026 <br>

In [2]:
# module  imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests

from io import BytesIO
from zipfile import ZipFile

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [4]:
#read in data
df = pd.read_csv("daily_aqi_by_county_2026.csv")
print("Rows and columns:", df.shape)
df.head()

Rows and columns: (77795, 10)

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2026-01-01,65,Moderate,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2026-01-02,25,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2026-01-03,40,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2026-01-04,39,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2026-01-05,41,Good,PM2.5,01-003-0010,1

In [5]:
# data
print(df.columns.tolist())
print(df.isna().sum())

df[[
    "Date",
    "State Name",
    "county Name",
    "AQI",
    "Category",
    "Defining Parameter",
    "Number of Sites Reporting"
]].head()

['State Name', 'county Name', 'State Code', 'County Code', 'Date', 'AQI', 'Category', 'Defining Parameter', 'Defining Site', 'Number of Sites Reporting']
State Name                   0
county Name                  0
State Code                   0
County Code                  0
Date                         0
AQI                          0
Category                     0
Defining Parameter           0
Defining Site                0
Number of Sites Reporting    0
dtype: int64

,Date,State Name,county Name,AQI,Category,Defining Parameter,Number of Sites Reporting
0,2026-01-01,Alabama,Baldwin,65,Moderate,PM2.5,1
1,2026-01-02,Alabama,Baldwin,25,Good,PM2.5,1
2,2026-01-03,Alabama,Baldwin,40,Good,PM2.5,1
3,2026-01-04,Alabama,Baldwin,39,Good,PM2.5,1
4,2026-01-05,Alabama,Baldwin,41,Good,PM2.5,1